language: python
python:
  - "3.5"

install: pip install -r requirements.txt

script:
    make html

after_success:
  - ghp-import -b gh-pages -n build/html -m 'abc'
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages --force
